config/routes.rb
Clearview::Application.routes.draw do
  
  resources :technicians

  root 'pages#home' #Index/Home Page
  devise_for :users
  
  get "about" => "pages#about" #About page route for /about
  get "change_log" => "pages#change_log" #Add ChangeLog for /change_log
  
  

  

end

app/models/technician.rb
class Technician < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController
  before_action :set_technician, only: [:show, :edit, :update, :destroy]

  # GET /technicians
  # GET /technicians.json
  def index
    @technicians = Technician.all
  end

  # GET /technicians/1
  # GET /technicians/1.json
  def show
  end

  # GET /technicians/new
  def new
    @technician = Technician.new
  end

  # GET /technicians/1/edit
  def edit
  end

  # POST /technicians
  # POST /technicians.json
  def create
    @technician = Technician.new(technician_params)

    respond_to do |format|
      if @technician.save
        format.html { redirect_to @technician, notice: 'Technician was successfully created.' }
        format.json { render action: 'show', status: :created, location: @technician }
      else
        format.html { render action: 'new' }
        format.json { render json: @technician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technicians/1
  # PATCH/PUT /technicians/1.json
  def update
    respond_to do |format|
      if @technician.update(technician_params)
        format.html { redirect_to @technician, notice: 'Technician was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @technician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technicians/1
  # DELETE /technicians/1.json
  def destroy
    @technician.destroy
    respond_to do |format|
      format.html { redirect_to technicians_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technician
      @technician = Technician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technician_params
      params.require(:technician).permit(:name, :location, :techid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/views/layouts/_footer.html.erb
			<div class="well infowell">
				<p>&copy; 2013 Andrew Fomera <%= link_to "Change Log", change_log_path %></p>
			</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container"> 
 <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "ClearInventory", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>

         <% if user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- End Container to help pull in navbar content-->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClearInventory | Inventory Management Done Right</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

   <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	
	<div class="container">

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>

		
		<%= render 'layouts/footer' %>
	</div>


</body>
</html>

app/views/pages/_change_log.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">
		<h5>v.0.0.0.3 - 11/15/2013 | 10 P.M</h5>
	</div>
	<div class="panel-body">
		<p><strong>Things Changed:</strong></p>
		<ul>
			<li>Started to add User Accounts using Devise</li>
			<li>Changed Default Font back to Lato instead of Chivo (which is secondary if Lato doesn't exist anymore)</li>
			<li>Will only post the last 5 versions on change log page until I can get it paginated</li>
		</ul>
	</div>	
</div>
<div class="panel panel-info">
	<div class="panel-heading">
		<h5>v.0.0.0.2 - 11/15/2013 | 8 P.M</h5>
	</div>
	<div class="panel-body">
		<p><strong>Things Changed:</strong></p>
		<ul>
			<li>About Page</li>
			<li>Change Log Page</li>
		</ul>
	</div>	
</div>

<div class="panel panel-info">
	<div class="panel-heading">
		<h5>v.0.0.0.1 - 11/15/2013 | 6 P.M</h5>
	</div>
	<div class="panel-body">
		<p><strong>Things Changed:</strong></p>
		<ul>
			<li>Created Rails Project</li>
			<li>About Page</li>
			<li>Contact Page</li>
			<li>Bootstrap Gems/Stylesheets</li>
		</ul>
	</div>	
</div>

app/views/pages/about.html.erb
<div class="well">
	<div class="page-header">
		<h1>About ClearInventory</h1>
	</div>

	<div class="row">
		<div class="col-md-8">
				<p>This application serves two purposes currently, the first is tracking the technicians we have and the second is storing images of labels we assign to the technicians.</p>

			<p>Eventually the goal is to handle the inventory automatically through uploading an image and selecting the tech, which it should then dump into the system.</p>
		</div>
		<div class="col-md-4 center">
		  		<div class="well infowell">
					<h4><Strong>Important Information</strong></h4>
		 			<p><strong>Having Issues?</strong> Call Andrew</p>

	        		<%= link_to "Back Home", root_path %>
		  		</div>
		 </div>

	</div>
</div>

app/views/pages/change_log.html.erb
<div class="well">
	<div class="page-header">
		<h1>Change Log</h1>
	</div>

			<p>This page reflects the changes we make to our site. It is not automatically updated and has to be done manually. It may not be up to date, though we will try to keep it updated.</p>
			

			<%= render 'pages/change_log' %>
</div>

app/views/pages/home.html.erb
<div class="well">
	<div class="jumbotron center">
		<h1>Welcome to ClearInventory!</h1>

		 <% if user_signed_in? %>

		 	<p>User is signed in, so display notices here</p>

		 	This could be notices of matches in inventory, or count of unmactched radios and modems
        <% else %>
	        <%= link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg" %>
			<%= link_to "Register", new_user_registration_path, class: "btn btn-success btn-lg" %>
        <% end %>
    </ul>
		
	</div>

	<div class="center">
		<p>This is content inside of the well, but outside of the jumbotron. How are you guys doing today?</p>
 		 <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-home large-image"></span>
            <% end %>
 		 <%= link_to new_user_session_path do %>
		<span class="glyphicon glyphicon-link large-image"></span> 
		    <% end %>
	</div>
</div>

app/views/technicians/_form.html.erb
<%= form_for(@technician) do |f| %>
  <% if @technician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technician.errors.count, "error") %> prohibited this technician from being saved:</h2>

      <ul>
      <% @technician.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel-body">
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :location %><br>
      <%= f.text_field :location %>
    </div>
    <div class="form-group">
      <%= f.label :techid %><br>
      <%= f.text_field :techid %>
    </div>
   <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/technicians/edit.html.erb
<h1>Edit technician</h1>

<%= render 'form' %>

<%= link_to 'Show', @technician %> |
<%= link_to 'Back', technicians_path %>

app/views/technicians/index.html.erb
<div class="well">
  <div class="page-header">
    <h1>Showing technicians</h1>
  </div>

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Name:</th>
        <th>Location:</th>
        <th>Tech ID:</th>
        <th>Actions:</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @technicians.each do |technician| %>
        <tr>
          <td><%= technician.name %></td>

          <td><%= technician.location %></td>
          <td><%= technician.techid %></td>
          <td><%= link_to 'Show', technician %></td>
          <td><%= link_to 'Edit', edit_technician_path(technician) %></td>
          <td><%= link_to 'Destroy', technician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New Technician', new_technician_path %>
</div>

app/views/technicians/new.html.erb
<div class="well">
	<h1>New technician</h1>

		<%= render 'form' %>

		<%= link_to 'Back', technicians_path %>
</div>

app/views/technicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @technician.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @technician.location %>
</p>

<p>
  <strong>Techid:</strong>
  <%= @technician.techid %>
</p>

<%= link_to 'Edit', edit_technician_path(@technician) %> |
<%= link_to 'Back', technicians_path %>